title: My Awesome Title
author: slymnGms
email: suleyman_gumus@outlook.com.tr
description: > # this means to ignore newlines until "baseurl:"
  My Awesome description for the website.
  As a developer/designer/system specialist,
  Let's dance in the fire...

# social links
github_username:  slymnGms # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
